server:
  port: 40000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: cart
          uri: lb://cart
          predicates:
            - Path= /cart/**
        - id: deliveryAddress
          uri: lb://deliveryAddress
          predicates:
            - Path= /deliveryAddress/**
        - id: food
          uri: lb://food
          predicates:
            - Path= /food/**
        - id: orders
          uri: lb://orders
          predicates:
            - Path= /orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuitBreakerA
                fallbackUri: forward:/fallback/orders
        - id: user
          uri: lb://user
          predicates:
            - Path= /user/**
        - id: business
          uri: lb://business
          predicates:
            - Path= /business/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader= Access-Control-Allow-Credentials Access-Control-Allow-Origin
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eureka28000:28000/eureka,http://eureka28001:28001/eureka"
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: TIME_BASED
        wait-duration-in-open-state: 5s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      circuitBreakerA:
        failureRateThreshold: 30