server:
  port: 10000
spring:
  application:
    name: "Provider"
  datasource:
    url: jdbc:mysql://localhost:3306/elm_jpa?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate.ddl-auto: update
      show-sql: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eureka28000:28000/eureka,http://eureka28001:28001/eureka"